# Generated by Django 4.0.6 on 2022-08-13 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0011_alter_participant_motivation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.speaker'),
        ),
    ]
